# Generated by Django 5.2.2 on 2025-06-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
